### ISSUE TITLE
Score metric tracking

### ISSUE THREAD

**Issue by Braekpo1nt** [Braekpo1nt/MCTManager#434]
## Description
Shotgun would ideally like to be able to have a csv file available for scores over the course of the event. Base scores without modifiers should be saved, for balanced metric tracking (but modifiers should be tracked alongside it just in case). Ideally, I would want a few different ways of representing the file.

- Each score awarded, with a time stamp, and who it was awarded to (and whether it was a player or a team)
  - Track whether the score was undone or not
  ```
  Target, Target Type, Score, Timestamp, Context, Reason, Multiplier
  Braekpo1nt, Player, 75, 6/4/24 4:25:240, MECHA, Kill, 1.0
  ```
- Also a more simplified version involving where the x axis is the player, the y axis is what game, and the value is what score they got (un-multiplied)
- Ask SgtShotgun what data he wants and in what format

## Definition of Done
- [ ] Scores are saved during the event
- [ ] Score metrics are available at the end of the event

**Comment by Braekpo1nt** [comment]
- [ ] make it so you can reload the hubConfig.json

**Comment by Braekpo1nt** [comment]
- [ ] ability to restrict how many arenas can be created
  - for practice mode where you can only have one arena
- [ ] simplify the placement of locations inside the arena
  - [ ] remove `"firstArenaOrigin"` and make a bounding box of ArenaDTO which is absolute coordinates of the first arena placed. 
  - [ ] everything within `ArenaDTO` is absolute coordinates (e.g. spawn is`1,2,3` not `firstArenaOrigin`+`1,2,3`
  - [ ] everything must be within the arena bounding box for validation
  - [ ] everything within `Arena` is absolute coordinates

**Comment by Braekpo1nt** [comment]
Completed in another issue #800
