### ISSUE TITLE
Practice Hub [Epic]

### ISSUE THREAD

**Issue by Braekpo1nt** [Braekpo1nt/MCTManager#657]
## Description
As a participant, I want to be able to play special versions of specific games in the hub, so that I can get practice and entertain my viewers during down-time.

## Requirements
- [x] Multiple practice games can be going on at once (e.g. some are practicing Spleef, some are practicing Parkour Pathway)
- [x] Points
  - [x] Points are tracked and displayed in the practice session
  - [x] Points are not actually awarded and don't impact the actual scores
- [x] Game Picker UI
  - [x] allows players to pick which team they are on
  - [x] allows players to invite teams to play a game
    - [x] teams get a chat message allowing them to accept
    - [x] player who sent the invite can start the game (or attempt to) before all teams have accepted, if the others are taking too long
  - [x] allows teams to join in on a game mid-way through
- [x] Version is updated because of the breaking changes this introduces to the GameState and other config files
- [x] Leave/join
  - [x] Participants who join are sent to the hub
- [x] games automatically stop when there are no more participants (i.e. all have logged off or left the hub)

## Config
Data that needs to come from practice/ config files

- [x] Which config files each game should use
- [x] Which games players are allowed to play
- [x] config specifies default starting state (practice, event, maintenance)
- [x] config specifies whether to reset scores on switching to and from practice state
- [x] Whitelist
  - [x] config specifies a preset to apply
  - [x] config specifies auto-whitelist and auto-un-whitelist flags
  - [x] on switching to practice mode auto-whitelist (if config allows)
  - [x] on switching from practice mode to maintenance mode auto-un-whitelist (if config allows)

**Comment by Braekpo1nt** [comment]
- [ ] can't create an invite for an in-progress games
- [ ] can't create an invite for a game that has an invite in-progress
- [ ] can't invite teams that are in-game (at least one player on that team being in-game means they're not qualified. Make this clear in the UI so players aren't wondering why they can't invite a specific team)
- [ ] can't invite teams that are in the middle of an active invite (sending or receiving)
- [ ] declining an invite removes the team from the active invite, allowing them to initiate their own invite or receive other invites
- [ ] teams who have a standing invite can't create or receive new invites
- [ ] players whose team is in a game can't create a new invite (otherwise that team might be sent to multiple games)
